development:
    dialect: mysql
    datasource: root:nghinv@/kom?parseTime=true
    dir: migrations
    table: migrations

production:
    dialect: mysql
    datasource: root:nghinv@/kom?parseTime=true
    dir: migrations
    table: migrations